// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10TN3YtDzGRsuCsIAyKEs9EwrtF42xRQ',
    appId: '1:323388033463:web:8b8589ff16bfc577920032',
    messagingSenderId: '323388033463',
    projectId: 'chatappflutter-5b0a8',
    authDomain: 'chatappflutter-5b0a8.firebaseapp.com',
    storageBucket: 'chatappflutter-5b0a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8HKa4-1IXcmaNW8KAhD8dZZeS3veVEw',
    appId: '1:323388033463:android:8a6b8041d8959f9e920032',
    messagingSenderId: '323388033463',
    projectId: 'chatappflutter-5b0a8',
    storageBucket: 'chatappflutter-5b0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdfu5h2tlIm04woT8S9_Okf__RU85R7P0',
    appId: '1:323388033463:ios:9f2567135d44a247920032',
    messagingSenderId: '323388033463',
    projectId: 'chatappflutter-5b0a8',
    storageBucket: 'chatappflutter-5b0a8.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdfu5h2tlIm04woT8S9_Okf__RU85R7P0',
    appId: '1:323388033463:ios:1dc4fbb80fc594d5920032',
    messagingSenderId: '323388033463',
    projectId: 'chatappflutter-5b0a8',
    storageBucket: 'chatappflutter-5b0a8.appspot.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
